steps:
  # 1단계(docker-compose -f docker-compose.prod.yaml build)
  - name: docker/compose:1.29.0
    args:
      - -f  
      - backend/docker-compose.prod.yaml
      - build

  # 2단계( docker-compose -f docker-compose.prod.yaml push)
  - name: docker/compose:1.29.0
    args:
      - -f  
      - backend/docker-compose.prod.yaml
      - push

  # 3단계( kubectl set image deployment/mybackend my-backend-sha256-1=asia.gcr.io/thinking-device-380708/my-backend:1.5)
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/mybackend
      - my-backend-sha256-1=asia.gcr.io/thinking-device-380708/my-backend:2.4
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-2