version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/myfolder/src
    env_file:
      - .env
    ports:
      - 3000:3000

  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydocker03'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  my-nginx:
    image: nginx:latest
    volumes:
      - ../frontend/html:/usr/share/nginx/html
    ports:
      - 80:80