version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/thinking-device-380708/my-backend:2.4.1
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    # env_file:
    #   - .env.prod
    ports:
      - 3000:3000

  # my-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker03'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306

  # my-redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379

  # my-nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ../frontend/html.prod:/usr/share/nginx/html
  #   ports:
  #     - 80:80